POST  http://127.0.0.1:3000/auth/signin


###

POST http://127.0.0.1:3000/auth/signup
content-type: application/json

{"firstname":"ahmed 1232","lastname":"ayman","password":"asd","email": "a@a.com","id":5}
